qcacld-3.0: Fix undeclared identifier STA_ENTRY_TDLS_PEER
STA_ENTRY_TDLS_PEER is defined under feature flag FEATURE_WLAN_TDLS.
With FEATURE_WLAN_TDLS=n, compiler throws use of undeclared identifier
'STA_ENTRY_TDLS_PEER'.

Hence fix the error in wma_he.c:1276 introduced in change
I16073a51a8949093872f7a421e0ad01648b63e92.

Change-Id: I0038dad70147b5c4ded2abad34baf50c8bc32f83
CRs-Fixed: 3275175