qcacmn: Use different assertion naming
Use different assertion name as same assertion name
is being used in more than once instance.

Fixed below error:
error: redefinition of typedef 'struct_size_4byte_assertion'
is a C11 feature [-Werror,-Wtypedef-redefinition]

Change-Id: I5809172a599123705b50613aae825a29433a4ba3
CRs-Fixed: 3357183